### PR TITLE
Count column nulls  issue14

### PR DESCRIPTION
**Pull request by nswitanek**
Looking for feedback on function to count null values across all columns -- one way of resolving feature issue #14 .

### CODE REVIEW

**Comment by grigory93** [comment]
I understood that function counts NULLs for each (or selected) columns in a table and returns data frame <column_name, null_count>.

This got to run  in a single SELECT like this:

```
 select count(*) row_count, count(column1) column1, count(column2) column2, 
           count(column3) column3, .... 
   from table_name;
```

We can introduce function _getNullCounts_ and export it as well.
It should follow parameter convention in _getTableSummary_, in particular for _include_ and _except_ and reuse standard handling of table name (_normalizeTableName_), column list (_sqlColumns_) used in this function.

It belongs to **utils.R**.

**Comment by grigory93** [comment]
You can use _mock_ (just like in _getTableSummary_ to avoid running _sqlColumns_ against live connection) and return SQL. Then you can write tests. 

Mock fakes table info for one of 2 tables: **pitching** and **batting**. but we can go over this later.

**Comment by nswitanek** [comment]
to do:
- [x] change function to match gregory's spec proposed in issues comment
- [x] use sqlColumns from RODBC
- [x] change SQL to avoid loop and get all column null counts directly
- [x] move function from separate script into utils.R
- [x] add tableInfo parameter (saving result of sqlColumns to tableInfo if not exists)
- [x] add test parameter
- [ ] write tests

**Comment by grigory93** [comment]
See my changes: added output parameter, docs, tests, import.

**Comment by grigory93** [comment]
Nick, while polishing this function I discovered a nasty bug with the way table names are resolved across Aster database. I have introduced solution into this function only - but it should be used across all other functions. I am still finalizing code and tests - should be checking in today. Please get the latest for the branch after I commit later today, run your checks, make sure it works as you designed and let me know. Then we can introduce it into develop branch.

**Pull request merged**
